# Form implementation generated from reading ui file 'ui/LLM_Config.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LLM_ConfigurationWidget(object):
    def setupUi(self, LLM_ConfigurationWidget):
        LLM_ConfigurationWidget.setObjectName("LLM_ConfigurationWidget")
        LLM_ConfigurationWidget.resize(1280, 797)
        LLM_ConfigurationWidget.setStyleSheet("QWidget {\n"
"    background-color: #1e1e1e;\n"
"    color: #d0d0d0;\n"
"    font-family: \"JetBrains Mono\", \"Fira Code\", \"Consolas\", monospace;\n"
"    font-size: 12pt;\n"
"    border: none;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #444;\n"
"    border-radius: 3px;\n"
"    margin-top: 5px;\n"
"    padding: 3px;\n"
"    font-weight: bold;\n"
"    color: #89f7fe;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 2px;\n"
"}\n"
"\n"
"QFrame {\n"
"    border: 1px solid #333;\n"
"    background-color: #121212;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #a0a0a0;\n"
"}\n"
"\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #262626;\n"
"    color: #f0f0f0;\n"
"    border: 1px solid #444;\n"
"    border-radius: 2px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #89f7fe;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #262626;\n"
"    color: #f0f0f0;\n"
"    border: 1px solid #444;\n"
"    padding: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #89f7fe;\n"
"}\n"
"\n"
"QSpinBox, QDoubleSpinBox {\n"
"    background-color: #262626;\n"
"    color: #f0f0f0;\n"
"    border: 1px solid #444;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button,\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    border: 1px solid #555;\n"
"    padding: 6px 12px;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"    border: 1px solid #89f7fe;\n"
"    color: #89f7fe;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1b1b1b;\n"
"    border: 1px solid #f50;\n"
"    color: #f50;\n"
"}\n"
"\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: #1e1e1e;\n"
"    border: none;\n"
"    width: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: #333;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background: #89f7fe;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background: none;\n"
"    height: 0px;\n"
"    width: 0px;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(LLM_ConfigurationWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputLLM_Frame = QtWidgets.QFrame(parent=LLM_ConfigurationWidget)
        self.inputLLM_Frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.inputLLM_Frame.setObjectName("inputLLM_Frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inputLLM_Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputLLM_GB = QtWidgets.QGroupBox(parent=self.inputLLM_Frame)
        self.inputLLM_GB.setObjectName("inputLLM_GB")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inputLLM_GB)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputLLM_OverlayWidget = QtWidgets.QWidget(parent=self.inputLLM_GB)
        self.inputLLM_OverlayWidget.setObjectName("inputLLM_OverlayWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.inputLLM_OverlayWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.loadDatasetBtn = QtWidgets.QPushButton(parent=self.inputLLM_OverlayWidget)
        self.loadDatasetBtn.setObjectName("loadDatasetBtn")
        self.horizontalLayout_5.addWidget(self.loadDatasetBtn)
        self.createAgent_DecomposerBtn = QtWidgets.QPushButton(parent=self.inputLLM_OverlayWidget)
        self.createAgent_DecomposerBtn.setObjectName("createAgent_DecomposerBtn")
        self.horizontalLayout_5.addWidget(self.createAgent_DecomposerBtn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.inputLLM_ResponseWindowFrame = QtWidgets.QFrame(parent=self.inputLLM_OverlayWidget)
        self.inputLLM_ResponseWindowFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.inputLLM_ResponseWindowFrame.setObjectName("inputLLM_ResponseWindowFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.inputLLM_ResponseWindowFrame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.inputLLM_ResponseWindowTE = QtWidgets.QTextEdit(parent=self.inputLLM_ResponseWindowFrame)
        self.inputLLM_ResponseWindowTE.setObjectName("inputLLM_ResponseWindowTE")
        self.verticalLayout_12.addWidget(self.inputLLM_ResponseWindowTE)
        self.verticalLayout_7.addWidget(self.inputLLM_ResponseWindowFrame)
        self.inputLLM_UserInputFrame = QtWidgets.QFrame(parent=self.inputLLM_OverlayWidget)
        self.inputLLM_UserInputFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.inputLLM_UserInputFrame.setObjectName("inputLLM_UserInputFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.inputLLM_UserInputFrame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.inputLLM_UserInputTE = QtWidgets.QTextEdit(parent=self.inputLLM_UserInputFrame)
        self.inputLLM_UserInputTE.setObjectName("inputLLM_UserInputTE")
        self.verticalLayout_11.addWidget(self.inputLLM_UserInputTE)
        self.verticalLayout_7.addWidget(self.inputLLM_UserInputFrame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mainMenuBtn = QtWidgets.QPushButton(parent=self.inputLLM_OverlayWidget)
        self.mainMenuBtn.setObjectName("mainMenuBtn")
        self.horizontalLayout_3.addWidget(self.mainMenuBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.inputLLM_StopBtn = QtWidgets.QPushButton(parent=self.inputLLM_OverlayWidget)
        self.inputLLM_StopBtn.setObjectName("inputLLM_StopBtn")
        self.horizontalLayout_3.addWidget(self.inputLLM_StopBtn)
        self.inputLLM_SendBtn = QtWidgets.QPushButton(parent=self.inputLLM_OverlayWidget)
        self.inputLLM_SendBtn.setObjectName("inputLLM_SendBtn")
        self.horizontalLayout_3.addWidget(self.inputLLM_SendBtn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.setStretch(1, 60)
        self.verticalLayout_7.setStretch(2, 30)
        self.verticalLayout_2.addWidget(self.inputLLM_OverlayWidget)
        self.verticalLayout.addWidget(self.inputLLM_GB)
        self.horizontalLayout.addWidget(self.inputLLM_Frame)
        self.controllerFrame = QtWidgets.QFrame(parent=LLM_ConfigurationWidget)
        self.controllerFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.controllerFrame.setObjectName("controllerFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.controllerFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inputLLM_ControllerFrame = QtWidgets.QFrame(parent=self.controllerFrame)
        self.inputLLM_ControllerFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.inputLLM_ControllerFrame.setObjectName("inputLLM_ControllerFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.inputLLM_ControllerFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.inputLLM_ControllerGB = QtWidgets.QGroupBox(parent=self.inputLLM_ControllerFrame)
        self.inputLLM_ControllerGB.setObjectName("inputLLM_ControllerGB")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.inputLLM_ControllerGB)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.inputLLM_ModelLabel = QtWidgets.QLabel(parent=self.inputLLM_ControllerGB)
        self.inputLLM_ModelLabel.setObjectName("inputLLM_ModelLabel")
        self.verticalLayout_10.addWidget(self.inputLLM_ModelLabel)
        self.inputLLM_ModelCB = QtWidgets.QComboBox(parent=self.inputLLM_ControllerGB)
        self.inputLLM_ModelCB.setObjectName("inputLLM_ModelCB")
        self.inputLLM_ModelCB.addItem("")
        self.inputLLM_ModelCB.addItem("")
        self.inputLLM_ModelCB.addItem("")
        self.inputLLM_ModelCB.addItem("")
        self.inputLLM_ModelCB.addItem("")
        self.inputLLM_ModelCB.addItem("")
        self.inputLLM_ModelCB.addItem("")
        self.inputLLM_ModelCB.addItem("")
        self.inputLLM_ModelCB.addItem("")
        self.inputLLM_ModelCB.addItem("")
        self.verticalLayout_10.addWidget(self.inputLLM_ModelCB)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.inputOpenAI_GB = QtWidgets.QGroupBox(parent=self.inputLLM_ControllerGB)
        self.inputOpenAI_GB.setObjectName("inputOpenAI_GB")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.inputOpenAI_GB)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.temperatureLabel = QtWidgets.QLabel(parent=self.inputOpenAI_GB)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.verticalLayout_15.addWidget(self.temperatureLabel)
        self.inputLLM_TemperatureSB = QtWidgets.QDoubleSpinBox(parent=self.inputOpenAI_GB)
        self.inputLLM_TemperatureSB.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.inputLLM_TemperatureSB.setDecimals(1)
        self.inputLLM_TemperatureSB.setMinimum(0.1)
        self.inputLLM_TemperatureSB.setMaximum(1.0)
        self.inputLLM_TemperatureSB.setSingleStep(0.1)
        self.inputLLM_TemperatureSB.setProperty("value", 0.5)
        self.inputLLM_TemperatureSB.setObjectName("inputLLM_TemperatureSB")
        self.verticalLayout_15.addWidget(self.inputLLM_TemperatureSB)
        self.inputLLM_TemperatureLabel = QtWidgets.QLabel(parent=self.inputOpenAI_GB)
        self.inputLLM_TemperatureLabel.setObjectName("inputLLM_TemperatureLabel")
        self.verticalLayout_15.addWidget(self.inputLLM_TemperatureLabel)
        self.inputLLM_PresencePenaltySB = QtWidgets.QSpinBox(parent=self.inputOpenAI_GB)
        self.inputLLM_PresencePenaltySB.setObjectName("inputLLM_PresencePenaltySB")
        self.verticalLayout_15.addWidget(self.inputLLM_PresencePenaltySB)
        self.inputLLM_FrequencyPenaltyLabel = QtWidgets.QLabel(parent=self.inputOpenAI_GB)
        self.inputLLM_FrequencyPenaltyLabel.setObjectName("inputLLM_FrequencyPenaltyLabel")
        self.verticalLayout_15.addWidget(self.inputLLM_FrequencyPenaltyLabel)
        self.inputLLM_FrequencyPenalySB = QtWidgets.QSpinBox(parent=self.inputOpenAI_GB)
        self.inputLLM_FrequencyPenalySB.setObjectName("inputLLM_FrequencyPenalySB")
        self.verticalLayout_15.addWidget(self.inputLLM_FrequencyPenalySB)
        self.inputLLM_TopPLabel = QtWidgets.QLabel(parent=self.inputOpenAI_GB)
        self.inputLLM_TopPLabel.setObjectName("inputLLM_TopPLabel")
        self.verticalLayout_15.addWidget(self.inputLLM_TopPLabel)
        self.inputLLM_TopKSB = QtWidgets.QDoubleSpinBox(parent=self.inputOpenAI_GB)
        self.inputLLM_TopKSB.setDecimals(1)
        self.inputLLM_TopKSB.setMinimum(0.1)
        self.inputLLM_TopKSB.setMaximum(1.0)
        self.inputLLM_TopKSB.setSingleStep(0.1)
        self.inputLLM_TopKSB.setProperty("value", 0.5)
        self.inputLLM_TopKSB.setObjectName("inputLLM_TopKSB")
        self.verticalLayout_15.addWidget(self.inputLLM_TopKSB)
        self.verticalLayout_10.addWidget(self.inputOpenAI_GB)
        self.inputLLM_TopKLabel = QtWidgets.QLabel(parent=self.inputLLM_ControllerGB)
        self.inputLLM_TopKLabel.setObjectName("inputLLM_TopKLabel")
        self.verticalLayout_10.addWidget(self.inputLLM_TopKLabel)
        self.inputLLM_TopKSB_3 = QtWidgets.QSpinBox(parent=self.inputLLM_ControllerGB)
        self.inputLLM_TopKSB_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.inputLLM_TopKSB_3.setMinimum(20)
        self.inputLLM_TopKSB_3.setMaximum(100)
        self.inputLLM_TopKSB_3.setProperty("value", 60)
        self.inputLLM_TopKSB_3.setObjectName("inputLLM_TopKSB_3")
        self.verticalLayout_10.addWidget(self.inputLLM_TopKSB_3)
        self.inputLLM_MinTokensLabel = QtWidgets.QLabel(parent=self.inputLLM_ControllerGB)
        self.inputLLM_MinTokensLabel.setObjectName("inputLLM_MinTokensLabel")
        self.verticalLayout_10.addWidget(self.inputLLM_MinTokensLabel)
        self.inputLLM_MinTokensLE = QtWidgets.QLineEdit(parent=self.inputLLM_ControllerGB)
        self.inputLLM_MinTokensLE.setObjectName("inputLLM_MinTokensLE")
        self.verticalLayout_10.addWidget(self.inputLLM_MinTokensLE)
        self.inputLLM_MaxTokensLabel = QtWidgets.QLabel(parent=self.inputLLM_ControllerGB)
        self.inputLLM_MaxTokensLabel.setObjectName("inputLLM_MaxTokensLabel")
        self.verticalLayout_10.addWidget(self.inputLLM_MaxTokensLabel)
        self.inputLLM_MaxTokenLE = QtWidgets.QLineEdit(parent=self.inputLLM_ControllerGB)
        self.inputLLM_MaxTokenLE.setObjectName("inputLLM_MaxTokenLE")
        self.verticalLayout_10.addWidget(self.inputLLM_MaxTokenLE)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.inputLLM_PingBtn = QtWidgets.QPushButton(parent=self.inputLLM_ControllerGB)
        self.inputLLM_PingBtn.setObjectName("inputLLM_PingBtn")
        self.verticalLayout_10.addWidget(self.inputLLM_PingBtn)
        self.verticalLayout_5.addWidget(self.inputLLM_ControllerGB)
        self.horizontalLayout_2.addWidget(self.inputLLM_ControllerFrame)
        self.outputLLM_ControllerFrame = QtWidgets.QFrame(parent=self.controllerFrame)
        self.outputLLM_ControllerFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.outputLLM_ControllerFrame.setObjectName("outputLLM_ControllerFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.outputLLM_ControllerFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.outputLLM_ControllerGB = QtWidgets.QGroupBox(parent=self.outputLLM_ControllerFrame)
        self.outputLLM_ControllerGB.setObjectName("outputLLM_ControllerGB")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.outputLLM_ControllerGB)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.outputLLM_ModelLabel = QtWidgets.QLabel(parent=self.outputLLM_ControllerGB)
        self.outputLLM_ModelLabel.setObjectName("outputLLM_ModelLabel")
        self.verticalLayout_9.addWidget(self.outputLLM_ModelLabel)
        self.outputModelCB = QtWidgets.QComboBox(parent=self.outputLLM_ControllerGB)
        self.outputModelCB.setObjectName("outputModelCB")
        self.outputModelCB.addItem("")
        self.outputModelCB.addItem("")
        self.outputModelCB.addItem("")
        self.outputModelCB.addItem("")
        self.outputModelCB.addItem("")
        self.outputModelCB.addItem("")
        self.outputModelCB.addItem("")
        self.outputModelCB.addItem("")
        self.outputModelCB.addItem("")
        self.outputModelCB.addItem("")
        self.verticalLayout_9.addWidget(self.outputModelCB)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.outputLLM_OpenAI_GB = QtWidgets.QGroupBox(parent=self.outputLLM_ControllerGB)
        self.outputLLM_OpenAI_GB.setObjectName("outputLLM_OpenAI_GB")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.outputLLM_OpenAI_GB)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.outputLLM_TemperatureLabel = QtWidgets.QLabel(parent=self.outputLLM_OpenAI_GB)
        self.outputLLM_TemperatureLabel.setObjectName("outputLLM_TemperatureLabel")
        self.verticalLayout_16.addWidget(self.outputLLM_TemperatureLabel)
        self.outputLLM_TemperatureSB = QtWidgets.QSpinBox(parent=self.outputLLM_OpenAI_GB)
        self.outputLLM_TemperatureSB.setObjectName("outputLLM_TemperatureSB")
        self.verticalLayout_16.addWidget(self.outputLLM_TemperatureSB)
        self.outputLLM_PresencePenaltyLabel = QtWidgets.QLabel(parent=self.outputLLM_OpenAI_GB)
        self.outputLLM_PresencePenaltyLabel.setObjectName("outputLLM_PresencePenaltyLabel")
        self.verticalLayout_16.addWidget(self.outputLLM_PresencePenaltyLabel)
        self.outputLLM_PresencePenaltySB = QtWidgets.QSpinBox(parent=self.outputLLM_OpenAI_GB)
        self.outputLLM_PresencePenaltySB.setObjectName("outputLLM_PresencePenaltySB")
        self.verticalLayout_16.addWidget(self.outputLLM_PresencePenaltySB)
        self.outputLLM_FrequencPenaltyLabel = QtWidgets.QLabel(parent=self.outputLLM_OpenAI_GB)
        self.outputLLM_FrequencPenaltyLabel.setObjectName("outputLLM_FrequencPenaltyLabel")
        self.verticalLayout_16.addWidget(self.outputLLM_FrequencPenaltyLabel)
        self.outputLLM_FrequencyPenaltySB = QtWidgets.QSpinBox(parent=self.outputLLM_OpenAI_GB)
        self.outputLLM_FrequencyPenaltySB.setObjectName("outputLLM_FrequencyPenaltySB")
        self.verticalLayout_16.addWidget(self.outputLLM_FrequencyPenaltySB)
        self.outputLLM_TopPLabel = QtWidgets.QLabel(parent=self.outputLLM_OpenAI_GB)
        self.outputLLM_TopPLabel.setObjectName("outputLLM_TopPLabel")
        self.verticalLayout_16.addWidget(self.outputLLM_TopPLabel)
        self.outputLLM_TopPSB = QtWidgets.QDoubleSpinBox(parent=self.outputLLM_OpenAI_GB)
        self.outputLLM_TopPSB.setDecimals(1)
        self.outputLLM_TopPSB.setMinimum(0.1)
        self.outputLLM_TopPSB.setMaximum(1.0)
        self.outputLLM_TopPSB.setSingleStep(0.1)
        self.outputLLM_TopPSB.setProperty("value", 0.5)
        self.outputLLM_TopPSB.setObjectName("outputLLM_TopPSB")
        self.verticalLayout_16.addWidget(self.outputLLM_TopPSB)
        self.verticalLayout_9.addWidget(self.outputLLM_OpenAI_GB)
        self.outputLL_TopKLabel = QtWidgets.QLabel(parent=self.outputLLM_ControllerGB)
        self.outputLL_TopKLabel.setObjectName("outputLL_TopKLabel")
        self.verticalLayout_9.addWidget(self.outputLL_TopKLabel)
        self.outputLLM_TopKSB = QtWidgets.QSpinBox(parent=self.outputLLM_ControllerGB)
        self.outputLLM_TopKSB.setMinimum(20)
        self.outputLLM_TopKSB.setMaximum(100)
        self.outputLLM_TopKSB.setProperty("value", 60)
        self.outputLLM_TopKSB.setObjectName("outputLLM_TopKSB")
        self.verticalLayout_9.addWidget(self.outputLLM_TopKSB)
        self.outputLLM_MinTokensLabel_2 = QtWidgets.QLabel(parent=self.outputLLM_ControllerGB)
        self.outputLLM_MinTokensLabel_2.setObjectName("outputLLM_MinTokensLabel_2")
        self.verticalLayout_9.addWidget(self.outputLLM_MinTokensLabel_2)
        self.outputLLM_MinTkensLE_2 = QtWidgets.QLineEdit(parent=self.outputLLM_ControllerGB)
        self.outputLLM_MinTkensLE_2.setObjectName("outputLLM_MinTkensLE_2")
        self.verticalLayout_9.addWidget(self.outputLLM_MinTkensLE_2)
        self.outputLLM_MaxTokensLabel_2 = QtWidgets.QLabel(parent=self.outputLLM_ControllerGB)
        self.outputLLM_MaxTokensLabel_2.setObjectName("outputLLM_MaxTokensLabel_2")
        self.verticalLayout_9.addWidget(self.outputLLM_MaxTokensLabel_2)
        self.outputLLM_MaxTokenLE_2 = QtWidgets.QLineEdit(parent=self.outputLLM_ControllerGB)
        self.outputLLM_MaxTokenLE_2.setObjectName("outputLLM_MaxTokenLE_2")
        self.verticalLayout_9.addWidget(self.outputLLM_MaxTokenLE_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.outputLLM_PingBtn = QtWidgets.QPushButton(parent=self.outputLLM_ControllerGB)
        self.outputLLM_PingBtn.setObjectName("outputLLM_PingBtn")
        self.verticalLayout_9.addWidget(self.outputLLM_PingBtn)
        self.verticalLayout_6.addWidget(self.outputLLM_ControllerGB)
        self.horizontalLayout_2.addWidget(self.outputLLM_ControllerFrame)
        self.horizontalLayout.addWidget(self.controllerFrame)
        self.outputLLM_Frame = QtWidgets.QFrame(parent=LLM_ConfigurationWidget)
        self.outputLLM_Frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.outputLLM_Frame.setObjectName("outputLLM_Frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.outputLLM_Frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.outputLLM_GB = QtWidgets.QGroupBox(parent=self.outputLLM_Frame)
        self.outputLLM_GB.setObjectName("outputLLM_GB")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.outputLLM_GB)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.outputLL_Widget = QtWidgets.QWidget(parent=self.outputLLM_GB)
        self.outputLL_Widget.setObjectName("outputLL_Widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.outputLL_Widget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.saveOutputBtn = QtWidgets.QPushButton(parent=self.outputLL_Widget)
        self.saveOutputBtn.setObjectName("saveOutputBtn")
        self.horizontalLayout_6.addWidget(self.saveOutputBtn)
        self.createAgent_ComposerBtn = QtWidgets.QPushButton(parent=self.outputLL_Widget)
        self.createAgent_ComposerBtn.setObjectName("createAgent_ComposerBtn")
        self.horizontalLayout_6.addWidget(self.createAgent_ComposerBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.outputLLM_ResponseWindowFrame = QtWidgets.QFrame(parent=self.outputLL_Widget)
        self.outputLLM_ResponseWindowFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.outputLLM_ResponseWindowFrame.setObjectName("outputLLM_ResponseWindowFrame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.outputLLM_ResponseWindowFrame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.outputLLM_ResponseWindowTE = QtWidgets.QTextEdit(parent=self.outputLLM_ResponseWindowFrame)
        self.outputLLM_ResponseWindowTE.setObjectName("outputLLM_ResponseWindowTE")
        self.verticalLayout_13.addWidget(self.outputLLM_ResponseWindowTE)
        self.verticalLayout_8.addWidget(self.outputLLM_ResponseWindowFrame)
        self.outputLLM_UserInputFrae = QtWidgets.QFrame(parent=self.outputLL_Widget)
        self.outputLLM_UserInputFrae.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.outputLLM_UserInputFrae.setObjectName("outputLLM_UserInputFrae")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.outputLLM_UserInputFrae)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.outputLLM_UserInputTE = QtWidgets.QTextEdit(parent=self.outputLLM_UserInputFrae)
        self.outputLLM_UserInputTE.setObjectName("outputLLM_UserInputTE")
        self.verticalLayout_14.addWidget(self.outputLLM_UserInputTE)
        self.verticalLayout_8.addWidget(self.outputLLM_UserInputFrae)
        self.verticalLayout_8.setStretch(1, 60)
        self.verticalLayout_8.setStretch(2, 30)
        self.verticalLayout_4.addWidget(self.outputLL_Widget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dashboardBtn = QtWidgets.QPushButton(parent=self.outputLLM_GB)
        self.dashboardBtn.setObjectName("dashboardBtn")
        self.horizontalLayout_4.addWidget(self.dashboardBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.outputLL_StopBtn = QtWidgets.QPushButton(parent=self.outputLLM_GB)
        self.outputLL_StopBtn.setObjectName("outputLL_StopBtn")
        self.horizontalLayout_4.addWidget(self.outputLL_StopBtn)
        self.outputLLM_SendBtn = QtWidgets.QPushButton(parent=self.outputLLM_GB)
        self.outputLLM_SendBtn.setObjectName("outputLLM_SendBtn")
        self.horizontalLayout_4.addWidget(self.outputLLM_SendBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.outputLLM_GB)
        self.horizontalLayout.addWidget(self.outputLLM_Frame)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(LLM_ConfigurationWidget)
        QtCore.QMetaObject.connectSlotsByName(LLM_ConfigurationWidget)

    def retranslateUi(self, LLM_ConfigurationWidget):
        _translate = QtCore.QCoreApplication.translate
        LLM_ConfigurationWidget.setWindowTitle(_translate("LLM_ConfigurationWidget", "LLM Configuration"))
        self.inputLLM_GB.setTitle(_translate("LLM_ConfigurationWidget", "Decomposer"))
        self.loadDatasetBtn.setText(_translate("LLM_ConfigurationWidget", "Load Dataset"))
        self.createAgent_DecomposerBtn.setText(_translate("LLM_ConfigurationWidget", "Create Agent"))
        self.mainMenuBtn.setText(_translate("LLM_ConfigurationWidget", "Main Menu"))
        self.inputLLM_StopBtn.setText(_translate("LLM_ConfigurationWidget", "Stop"))
        self.inputLLM_SendBtn.setText(_translate("LLM_ConfigurationWidget", "SEND"))
        self.inputLLM_ControllerGB.setTitle(_translate("LLM_ConfigurationWidget", "Input Controls"))
        self.inputLLM_ModelLabel.setText(_translate("LLM_ConfigurationWidget", "Input Model"))
        self.inputLLM_ModelCB.setItemText(0, _translate("LLM_ConfigurationWidget", "GPT-4o"))
        self.inputLLM_ModelCB.setItemText(1, _translate("LLM_ConfigurationWidget", "Claude 3"))
        self.inputLLM_ModelCB.setItemText(2, _translate("LLM_ConfigurationWidget", "Command R+"))
        self.inputLLM_ModelCB.setItemText(3, _translate("LLM_ConfigurationWidget", "Gemini"))
        self.inputLLM_ModelCB.setItemText(4, _translate("LLM_ConfigurationWidget", "Mistral"))
        self.inputLLM_ModelCB.setItemText(5, _translate("LLM_ConfigurationWidget", "Mistral 7B"))
        self.inputLLM_ModelCB.setItemText(6, _translate("LLM_ConfigurationWidget", "LLaMA 2"))
        self.inputLLM_ModelCB.setItemText(7, _translate("LLM_ConfigurationWidget", "GPT-3"))
        self.inputLLM_ModelCB.setItemText(8, _translate("LLM_ConfigurationWidget", "Nous Hermes"))
        self.inputLLM_ModelCB.setItemText(9, _translate("LLM_ConfigurationWidget", "Mythomax"))
        self.inputOpenAI_GB.setTitle(_translate("LLM_ConfigurationWidget", "OpenAI "))
        self.temperatureLabel.setText(_translate("LLM_ConfigurationWidget", "Temperature"))
        self.inputLLM_TemperatureLabel.setText(_translate("LLM_ConfigurationWidget", "Presence Penalty"))
        self.inputLLM_FrequencyPenaltyLabel.setText(_translate("LLM_ConfigurationWidget", "Frequency Penalty"))
        self.inputLLM_TopPLabel.setText(_translate("LLM_ConfigurationWidget", "Top-P"))
        self.inputLLM_TopKLabel.setText(_translate("LLM_ConfigurationWidget", "Top-K"))
        self.inputLLM_MinTokensLabel.setText(_translate("LLM_ConfigurationWidget", "Min. Tokens"))
        self.inputLLM_MaxTokensLabel.setText(_translate("LLM_ConfigurationWidget", "Max. Tokens"))
        self.inputLLM_PingBtn.setText(_translate("LLM_ConfigurationWidget", "Input Ping"))
        self.outputLLM_ControllerGB.setTitle(_translate("LLM_ConfigurationWidget", "Output Controls"))
        self.outputLLM_ModelLabel.setText(_translate("LLM_ConfigurationWidget", "Output Model"))
        self.outputModelCB.setItemText(0, _translate("LLM_ConfigurationWidget", "GPT-4o"))
        self.outputModelCB.setItemText(1, _translate("LLM_ConfigurationWidget", "Claude 3"))
        self.outputModelCB.setItemText(2, _translate("LLM_ConfigurationWidget", "Command R+"))
        self.outputModelCB.setItemText(3, _translate("LLM_ConfigurationWidget", "Gemini"))
        self.outputModelCB.setItemText(4, _translate("LLM_ConfigurationWidget", "Mistral"))
        self.outputModelCB.setItemText(5, _translate("LLM_ConfigurationWidget", "Mistral 7B"))
        self.outputModelCB.setItemText(6, _translate("LLM_ConfigurationWidget", "LLaMA 2"))
        self.outputModelCB.setItemText(7, _translate("LLM_ConfigurationWidget", "GPT-3"))
        self.outputModelCB.setItemText(8, _translate("LLM_ConfigurationWidget", "Nous Hermes"))
        self.outputModelCB.setItemText(9, _translate("LLM_ConfigurationWidget", "Mythomax"))
        self.outputLLM_OpenAI_GB.setTitle(_translate("LLM_ConfigurationWidget", "OpenAI "))
        self.outputLLM_TemperatureLabel.setText(_translate("LLM_ConfigurationWidget", "Temperature"))
        self.outputLLM_PresencePenaltyLabel.setText(_translate("LLM_ConfigurationWidget", "Presence Penalty"))
        self.outputLLM_FrequencPenaltyLabel.setText(_translate("LLM_ConfigurationWidget", "Frequency Penalty"))
        self.outputLLM_TopPLabel.setText(_translate("LLM_ConfigurationWidget", "Top-P"))
        self.outputLL_TopKLabel.setText(_translate("LLM_ConfigurationWidget", "Top-K"))
        self.outputLLM_MinTokensLabel_2.setText(_translate("LLM_ConfigurationWidget", "Min. Tokens"))
        self.outputLLM_MaxTokensLabel_2.setText(_translate("LLM_ConfigurationWidget", "Max. Tokens"))
        self.outputLLM_PingBtn.setText(_translate("LLM_ConfigurationWidget", "Output Ping"))
        self.outputLLM_GB.setTitle(_translate("LLM_ConfigurationWidget", "Composer"))
        self.saveOutputBtn.setText(_translate("LLM_ConfigurationWidget", "Save Output"))
        self.createAgent_ComposerBtn.setText(_translate("LLM_ConfigurationWidget", "Create Agent"))
        self.dashboardBtn.setText(_translate("LLM_ConfigurationWidget", "Dashboard"))
        self.outputLL_StopBtn.setText(_translate("LLM_ConfigurationWidget", "Stop"))
        self.outputLLM_SendBtn.setText(_translate("LLM_ConfigurationWidget", "SEND"))
