# Form implementation generated from reading ui file 'ui/Trace_Audits.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Audits(object):
    def setupUi(self, Audits):
        Audits.setObjectName("Audits")
        Audits.resize(1226, 1344)
        Audits.setStyleSheet("QWidget {\n"
"    background-color: #1e1e1e;\n"
"    color: #d0d0d0;\n"
"    font-family: \"JetBrains Mono\", \"Fira Code\", \"Consolas\", monospace;\n"
"    font-size: 12pt;\n"
"    border: none;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #444;\n"
"    border-radius: 3px;\n"
"    margin-top: 5px;\n"
"    padding: 3px;\n"
"    font-weight: bold;\n"
"    color: #89f7fe;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 2px;\n"
"}\n"
"\n"
"QFrame {\n"
"    border: 1px solid #333;\n"
"    background-color: #121212;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #a0a0a0;\n"
"}\n"
"\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #262626;\n"
"    color: #f0f0f0;\n"
"    border: 1px solid #444;\n"
"    border-radius: 2px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #89f7fe;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #262626;\n"
"    color: #f0f0f0;\n"
"    border: 1px solid #444;\n"
"    padding: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #89f7fe;\n"
"}\n"
"\n"
"QSpinBox, QDoubleSpinBox {\n"
"    background-color: #262626;\n"
"    color: #f0f0f0;\n"
"    border: 1px solid #444;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button,\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    border: 1px solid #555;\n"
"    padding: 6px 12px;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"    border: 1px solid #89f7fe;\n"
"    color: #89f7fe;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1b1b1b;\n"
"    border: 1px solid #f50;\n"
"    color: #f50;\n"
"}\n"
"\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: #1e1e1e;\n"
"    border: none;\n"
"    width: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: #333;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background: #89f7fe;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background: none;\n"
"    height: 0px;\n"
"    width: 0px;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Audits)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget = QtWidgets.QDockWidget(parent=Audits)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFeature.NoDockWidgetFeatures)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.controlsWidget = QtWidgets.QWidget(parent=self.dockWidgetContents)
        self.controlsWidget.setObjectName("controlsWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.controlsWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.resetBtn = QtWidgets.QPushButton(parent=self.controlsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetBtn.sizePolicy().hasHeightForWidth())
        self.resetBtn.setSizePolicy(sizePolicy)
        self.resetBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.resetBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.resetBtn.setObjectName("resetBtn")
        self.verticalLayout_5.addWidget(self.resetBtn)
        self.loadBtn = QtWidgets.QPushButton(parent=self.controlsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadBtn.sizePolicy().hasHeightForWidth())
        self.loadBtn.setSizePolicy(sizePolicy)
        self.loadBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.loadBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.loadBtn.setObjectName("loadBtn")
        self.verticalLayout_5.addWidget(self.loadBtn)
        self.saveBtn = QtWidgets.QPushButton(parent=self.controlsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveBtn.sizePolicy().hasHeightForWidth())
        self.saveBtn.setSizePolicy(sizePolicy)
        self.saveBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.saveBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.saveBtn.setObjectName("saveBtn")
        self.verticalLayout_5.addWidget(self.saveBtn)
        self.metadataBtn = QtWidgets.QPushButton(parent=self.controlsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadataBtn.sizePolicy().hasHeightForWidth())
        self.metadataBtn.setSizePolicy(sizePolicy)
        self.metadataBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.metadataBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.metadataBtn.setObjectName("metadataBtn")
        self.verticalLayout_5.addWidget(self.metadataBtn)
        self.printBtn = QtWidgets.QPushButton(parent=self.controlsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printBtn.sizePolicy().hasHeightForWidth())
        self.printBtn.setSizePolicy(sizePolicy)
        self.printBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.printBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.printBtn.setObjectName("printBtn")
        self.verticalLayout_5.addWidget(self.printBtn)
        self.backBtn = QtWidgets.QPushButton(parent=self.controlsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBtn.sizePolicy().hasHeightForWidth())
        self.backBtn.setSizePolicy(sizePolicy)
        self.backBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.backBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.backBtn.setObjectName("backBtn")
        self.verticalLayout_5.addWidget(self.backBtn)
        self.verticalLayout_4.addWidget(self.controlsWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.inputFactorsPhaseFrame = QtWidgets.QFrame(parent=Audits)
        self.inputFactorsPhaseFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.inputFactorsPhaseFrame.setObjectName("inputFactorsPhaseFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inputFactorsPhaseFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.originaInputGB = QtWidgets.QGroupBox(parent=self.inputFactorsPhaseFrame)
        self.originaInputGB.setObjectName("originaInputGB")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.originaInputGB)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.originalInputTE = QtWidgets.QTextEdit(parent=self.originaInputGB)
        self.originalInputTE.setObjectName("originalInputTE")
        self.verticalLayout_3.addWidget(self.originalInputTE)
        self.verticalLayout.addWidget(self.originaInputGB)
        self.rhetoricalArcGB = QtWidgets.QGroupBox(parent=self.inputFactorsPhaseFrame)
        self.rhetoricalArcGB.setObjectName("rhetoricalArcGB")
        self.formLayout_3 = QtWidgets.QFormLayout(self.rhetoricalArcGB)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignLeading)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout_3.setHorizontalSpacing(9)
        self.formLayout_3.setObjectName("formLayout_3")
        self.rhetoricalArcFormLabel = QtWidgets.QLabel(parent=self.rhetoricalArcGB)
        self.rhetoricalArcFormLabel.setObjectName("rhetoricalArcFormLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rhetoricalArcFormLabel)
        self.rhetoricalArcFrameLabel = QtWidgets.QLabel(parent=self.rhetoricalArcGB)
        self.rhetoricalArcFrameLabel.setObjectName("rhetoricalArcFrameLabel")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rhetoricalArcFrameLabel)
        self.rhetoricalArcRelationLabel = QtWidgets.QLabel(parent=self.rhetoricalArcGB)
        self.rhetoricalArcRelationLabel.setObjectName("rhetoricalArcRelationLabel")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rhetoricalArcRelationLabel)
        self.rhetoricalArcIntenLabel = QtWidgets.QLabel(parent=self.rhetoricalArcGB)
        self.rhetoricalArcIntenLabel.setObjectName("rhetoricalArcIntenLabel")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rhetoricalArcIntenLabel)
        self.rhetoricalArcActionTE = QtWidgets.QTextEdit(parent=self.rhetoricalArcGB)
        self.rhetoricalArcActionTE.setObjectName("rhetoricalArcActionTE")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rhetoricalArcActionTE)
        self.rhetoricalArcFormTE = QtWidgets.QTextEdit(parent=self.rhetoricalArcGB)
        self.rhetoricalArcFormTE.setObjectName("rhetoricalArcFormTE")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rhetoricalArcFormTE)
        self.rhetoricalArcFrameTE = QtWidgets.QTextEdit(parent=self.rhetoricalArcGB)
        self.rhetoricalArcFrameTE.setObjectName("rhetoricalArcFrameTE")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rhetoricalArcFrameTE)
        self.rhetoricalArcEssenceTE = QtWidgets.QTextEdit(parent=self.rhetoricalArcGB)
        self.rhetoricalArcEssenceTE.setObjectName("rhetoricalArcEssenceTE")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rhetoricalArcEssenceTE)
        self.rhetoricalArcEssenceLabel = QtWidgets.QLabel(parent=self.rhetoricalArcGB)
        self.rhetoricalArcEssenceLabel.setObjectName("rhetoricalArcEssenceLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rhetoricalArcEssenceLabel)
        self.rhetoricalArcActionsLabel = QtWidgets.QLabel(parent=self.rhetoricalArcGB)
        self.rhetoricalArcActionsLabel.setObjectName("rhetoricalArcActionsLabel")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rhetoricalArcActionsLabel)
        self.rhetoricalArcIntentTE = QtWidgets.QTextEdit(parent=self.rhetoricalArcGB)
        self.rhetoricalArcIntentTE.setObjectName("rhetoricalArcIntentTE")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rhetoricalArcIntentTE)
        self.rhetoricalArcRelationTE = QtWidgets.QTextEdit(parent=self.rhetoricalArcGB)
        self.rhetoricalArcRelationTE.setObjectName("rhetoricalArcRelationTE")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rhetoricalArcRelationTE)
        self.rhetoricalArcValueTE = QtWidgets.QTextEdit(parent=self.rhetoricalArcGB)
        self.rhetoricalArcValueTE.setObjectName("rhetoricalArcValueTE")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rhetoricalArcValueTE)
        self.rhetoricalArcValueLabel = QtWidgets.QLabel(parent=self.rhetoricalArcGB)
        self.rhetoricalArcValueLabel.setObjectName("rhetoricalArcValueLabel")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rhetoricalArcValueLabel)
        self.verticalLayout.addWidget(self.rhetoricalArcGB)
        self.postPipelineGP = QtWidgets.QGroupBox(parent=self.inputFactorsPhaseFrame)
        self.postPipelineGP.setObjectName("postPipelineGP")
        self.formLayout_2 = QtWidgets.QFormLayout(self.postPipelineGP)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignLeading)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout_2.setHorizontalSpacing(9)
        self.formLayout_2.setObjectName("formLayout_2")
        self.postPipleineTierLabel2 = QtWidgets.QLabel(parent=self.postPipelineGP)
        self.postPipleineTierLabel2.setObjectName("postPipleineTierLabel2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.postPipleineTierLabel2)
        self.postPipleineTierLabel4 = QtWidgets.QLabel(parent=self.postPipelineGP)
        self.postPipleineTierLabel4.setObjectName("postPipleineTierLabel4")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.postPipleineTierLabel4)
        self.postPipleineTierLabel6 = QtWidgets.QLabel(parent=self.postPipelineGP)
        self.postPipleineTierLabel6.setObjectName("postPipleineTierLabel6")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.postPipleineTierLabel6)
        self.postPipleineTierLabel5 = QtWidgets.QLabel(parent=self.postPipelineGP)
        self.postPipleineTierLabel5.setObjectName("postPipleineTierLabel5")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.postPipleineTierLabel5)
        self.postPipleineTierTE_3 = QtWidgets.QTextEdit(parent=self.postPipelineGP)
        self.postPipleineTierTE_3.setObjectName("postPipleineTierTE_3")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.postPipleineTierTE_3)
        self.postPipleineTierTE_2 = QtWidgets.QTextEdit(parent=self.postPipelineGP)
        self.postPipleineTierTE_2.setObjectName("postPipleineTierTE_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.postPipleineTierTE_2)
        self.postPipleineTierTE_4 = QtWidgets.QTextEdit(parent=self.postPipelineGP)
        self.postPipleineTierTE_4.setObjectName("postPipleineTierTE_4")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.postPipleineTierTE_4)
        self.postPipleineTierTE_1 = QtWidgets.QTextEdit(parent=self.postPipelineGP)
        self.postPipleineTierTE_1.setObjectName("postPipleineTierTE_1")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.postPipleineTierTE_1)
        self.postPipleineTierLabel1 = QtWidgets.QLabel(parent=self.postPipelineGP)
        self.postPipleineTierLabel1.setObjectName("postPipleineTierLabel1")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.postPipleineTierLabel1)
        self.postPipleineTierLabel3 = QtWidgets.QLabel(parent=self.postPipelineGP)
        self.postPipleineTierLabel3.setObjectName("postPipleineTierLabel3")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.postPipleineTierLabel3)
        self.postPipleineTierTE_5 = QtWidgets.QTextEdit(parent=self.postPipelineGP)
        self.postPipleineTierTE_5.setObjectName("postPipleineTierTE_5")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.postPipleineTierTE_5)
        self.postPipleineTierTE_6 = QtWidgets.QTextEdit(parent=self.postPipelineGP)
        self.postPipleineTierTE_6.setObjectName("postPipleineTierTE_6")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.postPipleineTierTE_6)
        self.postPipleineTierTE_7 = QtWidgets.QTextEdit(parent=self.postPipelineGP)
        self.postPipleineTierTE_7.setObjectName("postPipleineTierTE_7")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.postPipleineTierTE_7)
        self.postPipleineTierLabel7 = QtWidgets.QLabel(parent=self.postPipelineGP)
        self.postPipleineTierLabel7.setObjectName("postPipleineTierLabel7")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.postPipleineTierLabel7)
        self.verticalLayout.addWidget(self.postPipelineGP)
        self.horizontalLayout.addWidget(self.inputFactorsPhaseFrame)
        self.finalOutputResultsFrame = QtWidgets.QFrame(parent=Audits)
        self.finalOutputResultsFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.finalOutputResultsFrame.setObjectName("finalOutputResultsFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.finalOutputResultsFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OutputResultsGB = QtWidgets.QGroupBox(parent=self.finalOutputResultsFrame)
        self.OutputResultsGB.setObjectName("OutputResultsGB")
        self.formLayout_4 = QtWidgets.QFormLayout(self.OutputResultsGB)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignLeading)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout_4.setHorizontalSpacing(9)
        self.formLayout_4.setObjectName("formLayout_4")
        self.dynPopOutLabel_2 = QtWidgets.QLabel(parent=self.OutputResultsGB)
        self.dynPopOutLabel_2.setObjectName("dynPopOutLabel_2")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dynPopOutLabel_2)
        self.dynPopOutLabel_4 = QtWidgets.QLabel(parent=self.OutputResultsGB)
        self.dynPopOutLabel_4.setObjectName("dynPopOutLabel_4")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dynPopOutLabel_4)
        self.dynPopOutLabel_6 = QtWidgets.QLabel(parent=self.OutputResultsGB)
        self.dynPopOutLabel_6.setObjectName("dynPopOutLabel_6")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dynPopOutLabel_6)
        self.dynPopOutLabel_5 = QtWidgets.QLabel(parent=self.OutputResultsGB)
        self.dynPopOutLabel_5.setObjectName("dynPopOutLabel_5")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dynPopOutLabel_5)
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.OutputResultsGB)
        self.textEdit_3.setObjectName("textEdit_3")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_3)
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.OutputResultsGB)
        self.textEdit_2.setObjectName("textEdit_2")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_2)
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.OutputResultsGB)
        self.textEdit_4.setObjectName("textEdit_4")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_4)
        self.textEdit_1 = QtWidgets.QTextEdit(parent=self.OutputResultsGB)
        self.textEdit_1.setObjectName("textEdit_1")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_1)
        self.dynPopOutLabel_1 = QtWidgets.QLabel(parent=self.OutputResultsGB)
        self.dynPopOutLabel_1.setObjectName("dynPopOutLabel_1")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dynPopOutLabel_1)
        self.dynPopOutLabel_3 = QtWidgets.QLabel(parent=self.OutputResultsGB)
        self.dynPopOutLabel_3.setObjectName("dynPopOutLabel_3")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dynPopOutLabel_3)
        self.textEdit_5 = QtWidgets.QTextEdit(parent=self.OutputResultsGB)
        self.textEdit_5.setObjectName("textEdit_5")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_5)
        self.textEdit_6 = QtWidgets.QTextEdit(parent=self.OutputResultsGB)
        self.textEdit_6.setObjectName("textEdit_6")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_6)
        self.textEdit_7 = QtWidgets.QTextEdit(parent=self.OutputResultsGB)
        self.textEdit_7.setObjectName("textEdit_7")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_7)
        self.dynPopOutLabel_7 = QtWidgets.QLabel(parent=self.OutputResultsGB)
        self.dynPopOutLabel_7.setObjectName("dynPopOutLabel_7")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dynPopOutLabel_7)
        self.verticalLayout_2.addWidget(self.OutputResultsGB)
        self.horizontalLayout.addWidget(self.finalOutputResultsFrame)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 45)
        self.horizontalLayout.setStretch(2, 45)

        self.retranslateUi(Audits)
        QtCore.QMetaObject.connectSlotsByName(Audits)

    def retranslateUi(self, Audits):
        _translate = QtCore.QCoreApplication.translate
        Audits.setWindowTitle(_translate("Audits", "Audit"))
        self.resetBtn.setText(_translate("Audits", "Reset"))
        self.loadBtn.setText(_translate("Audits", "Load"))
        self.saveBtn.setText(_translate("Audits", "Save"))
        self.metadataBtn.setText(_translate("Audits", "Metadata"))
        self.printBtn.setText(_translate("Audits", "Print"))
        self.backBtn.setText(_translate("Audits", "Back"))
        self.originaInputGB.setTitle(_translate("Audits", "Original Input"))
        self.rhetoricalArcGB.setTitle(_translate("Audits", "Rhetorical Arcs Input"))
        self.rhetoricalArcFormLabel.setText(_translate("Audits", "Form"))
        self.rhetoricalArcFrameLabel.setText(_translate("Audits", "Frame"))
        self.rhetoricalArcRelationLabel.setText(_translate("Audits", "Relation"))
        self.rhetoricalArcIntenLabel.setText(_translate("Audits", "Intent"))
        self.rhetoricalArcEssenceLabel.setText(_translate("Audits", "Essence"))
        self.rhetoricalArcActionsLabel.setText(_translate("Audits", "Action"))
        self.rhetoricalArcValueLabel.setText(_translate("Audits", "Value"))
        self.postPipelineGP.setTitle(_translate("Audits", "Post Pipline"))
        self.postPipleineTierLabel2.setText(_translate("Audits", "Rank 2"))
        self.postPipleineTierLabel4.setText(_translate("Audits", "Rank 4"))
        self.postPipleineTierLabel6.setText(_translate("Audits", "Rank 6"))
        self.postPipleineTierLabel5.setText(_translate("Audits", "Rank 5"))
        self.postPipleineTierLabel1.setText(_translate("Audits", "Rank 1"))
        self.postPipleineTierLabel3.setText(_translate("Audits", "Rank 3"))
        self.postPipleineTierLabel7.setText(_translate("Audits", "Rank 7"))
        self.OutputResultsGB.setTitle(_translate("Audits", "Reconstructed Inference"))
        self.dynPopOutLabel_2.setText(_translate("Audits", "DArc+Tier"))
        self.dynPopOutLabel_4.setText(_translate("Audits", "DArc+Tier"))
        self.dynPopOutLabel_6.setText(_translate("Audits", "DArc+Tier"))
        self.dynPopOutLabel_5.setText(_translate("Audits", "DArc+Tier"))
        self.dynPopOutLabel_1.setText(_translate("Audits", "DArc+Tier"))
        self.dynPopOutLabel_3.setText(_translate("Audits", "DArc+Tier"))
        self.dynPopOutLabel_7.setText(_translate("Audits", "DArc+Tier"))
