# Form implementation generated from reading ui file 'ui/composer.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Comoser(object):
    def setupUi(self, Comoser):
        Comoser.setObjectName("Comoser")
        Comoser.resize(400, 300)
        Comoser.setStyleSheet("QWidget {\n"
"    background-color: #1e1e1e;\n"
"    color: #d0d0d0;\n"
"    font-family: \"JetBrains Mono\", \"Fira Code\", \"Consolas\", monospace;\n"
"    font-size: 12pt;\n"
"    border: none;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #444;\n"
"    border-radius: 3px;\n"
"    margin-top: 5px;\n"
"    padding: 3px;\n"
"    font-weight: bold;\n"
"    color: #89f7fe;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 2px;\n"
"}\n"
"\n"
"QFrame {\n"
"    border: 1px solid #333;\n"
"    background-color: #121212;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #a0a0a0;\n"
"}\n"
"\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #262626;\n"
"    color: #f0f0f0;\n"
"    border: 1px solid #444;\n"
"    border-radius: 2px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #89f7fe;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #262626;\n"
"    color: #f0f0f0;\n"
"    border: 1px solid #444;\n"
"    padding: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #89f7fe;\n"
"}\n"
"\n"
"QSpinBox, QDoubleSpinBox {\n"
"    background-color: #262626;\n"
"    color: #f0f0f0;\n"
"    border: 1px solid #444;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button,\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background-color: #2e2e2e;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2d2d2d;\n"
"    border: 1px solid #555;\n"
"    padding: 6px 12px;\n"
"    border-radius: 4px;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"    border: 1px solid #89f7fe;\n"
"    color: #89f7fe;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1b1b1b;\n"
"    border: 1px solid #f50;\n"
"    color: #f50;\n"
"}\n"
"\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: #1e1e1e;\n"
"    border: none;\n"
"    width: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: #333;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background: #89f7fe;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background: none;\n"
"    height: 0px;\n"
"    width: 0px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Comoser)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.outputLLM_API_KeyLabel = QtWidgets.QLabel(parent=Comoser)
        self.outputLLM_API_KeyLabel.setObjectName("outputLLM_API_KeyLabel")
        self.horizontalLayout_6.addWidget(self.outputLLM_API_KeyLabel)
        self.outputLLM_API_KeyLE = QtWidgets.QLineEdit(parent=Comoser)
        self.outputLLM_API_KeyLE.setObjectName("outputLLM_API_KeyLE")
        self.horizontalLayout_6.addWidget(self.outputLLM_API_KeyLE)
        self.composerAPI_SaveBtn = QtWidgets.QPushButton(parent=Comoser)
        self.composerAPI_SaveBtn.setObjectName("composerAPI_SaveBtn")
        self.horizontalLayout_6.addWidget(self.composerAPI_SaveBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.frame = QtWidgets.QFrame(parent=Comoser)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nameLabel = QtWidgets.QLabel(parent=self.frame)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout.addWidget(self.nameLabel)
        self.agentNameLE = QtWidgets.QLineEdit(parent=self.frame)
        self.agentNameLE.setObjectName("agentNameLE")
        self.horizontalLayout.addWidget(self.agentNameLE)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.agentID_Label = QtWidgets.QLabel(parent=self.frame)
        self.agentID_Label.setObjectName("agentID_Label")
        self.horizontalLayout_4.addWidget(self.agentID_Label)
        self.agentID_LE = QtWidgets.QLineEdit(parent=self.frame)
        self.agentID_LE.setObjectName("agentID_LE")
        self.horizontalLayout_4.addWidget(self.agentID_LE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.promptLabel = QtWidgets.QLabel(parent=self.frame)
        self.promptLabel.setObjectName("promptLabel")
        self.verticalLayout_2.addWidget(self.promptLabel)
        self.systemPromptTE = QtWidgets.QTextEdit(parent=self.frame)
        self.systemPromptTE.setObjectName("systemPromptTE")
        self.verticalLayout_2.addWidget(self.systemPromptTE)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelBtn = QtWidgets.QPushButton(parent=self.frame)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.updateBtn = QtWidgets.QPushButton(parent=self.frame)
        self.updateBtn.setObjectName("updateBtn")
        self.horizontalLayout_2.addWidget(self.updateBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Comoser)
        QtCore.QMetaObject.connectSlotsByName(Comoser)

    def retranslateUi(self, Comoser):
        _translate = QtCore.QCoreApplication.translate
        Comoser.setWindowTitle(_translate("Comoser", "Composer"))
        self.outputLLM_API_KeyLabel.setText(_translate("Comoser", "API_Key"))
        self.composerAPI_SaveBtn.setText(_translate("Comoser", "Save"))
        self.nameLabel.setText(_translate("Comoser", "Agent Name"))
        self.agentID_Label.setText(_translate("Comoser", "Agent ID"))
        self.promptLabel.setText(_translate("Comoser", "System Prompt"))
        self.cancelBtn.setText(_translate("Comoser", "Cancel"))
        self.updateBtn.setText(_translate("Comoser", "Update"))
